# ######################################################
# Last review            Thu 26 Jun 2014 09:48:02 AM CDT
# ######################################################
# vim: set ts=8 sw=4 tw=0 ft=sh:

# This file should only initialize the window manager
# use ~/.i3/startup to start additional programs

/etc/X11/Xsession i3

#exec i3                            # start i3 without /etc/X11/Xsession.d/ goodies (dbus, gpg-agent, etc)
#exec i3 >> ~/.i3/logfile           # start i3 with standard messages
#exec i3 -d all >> ~/.i3/logfile    # start i3 in debug mode
#exec i3 -V -d all >> ~/.i3/logfile # start i3 in super verbose mode
