! Dark III

! vim:enc=utf-8:nu:ai:si:et:ts=4:sw=4:ft=xdefaults:

*background: rgb:00/00/00
*foreground: rgb:cf/cf/cf
*color0  : #2E3436
*color1  : #a31604
*color2  : #447241
*color3  : #c1951a
*color4  : #425387
*color5  : #965d98
*color6  : #06989A
*color7  : #D3D7CF
*color8  : #555753
*color9  : #c60001
*color10 : #27a343
*color11 : #d5a30e
*color12 : #4a5a8d
*color13 : #893c8c
*color14 : #12bccb
*color15 : #EEEEEC
