#!/bin/sh

#to avoid errors for trying to start apps without an Xserver running
sleep .1s

#tab
conky | $HOME/code/dzen/dzen2 -dock -fn -xos4-terminus-medium-r-*-*-12-*-*-*-*-*-iso10646-1 -ta r -fg "#999999" -bg "#000000" &

#/usr/bin/x-terminal-emulator &
/usr/bin/pcmanfm &

#/usr/bin/workrave & #force to take a break ~/.workrave
#xwrits breaktime=0:20 typetime=5:00 +mouse +lock #helps to take a break every 5 min
#exec xsetroot -solid white
#exec xsetroot -cursor_name left_ptr

#urxvt server, nice but it breaks very often
#urxvtd -q -f -o

#background?
#feh --bg-scale $HOME/data/images/wallpapers/Aurora_Borealis.jpg
