#!/bin/sh

_exec()
{
    [ -z "${1}" ] && return 1
    if command -v "${1}" >/dev/null; then
        if ! pgrep -f "${1}" >/dev/null; then
            ${@} &
        fi
    else
        printf "%s\\n" "${1} was not found!" >&2
    fi
}

_execm()
{
    [ X"$(minos-config "${1#m-}" 2>/dev/null)" = X"no" ] && return
    _execm_var_tool="$(minos-config "${1}" 2>/dev/null)"
    if [ -z "${_execm_var_tool}" ]; then
        shift; _exec ${@}
    else
        _exec ${_execm_var_tool}; _execm_var_tool=""
    fi
}

#TODO 23-12-2014 16:44 >> fix it
_exec i3-msg workspace "1 www" # force to start on first virtual workspace

#_exec mplayer -loop 0 -rootwin -ao null -noconsolecontrols video.mp4 # video background
wallpaper="$(minos-config wallpaper 2>/dev/null)"
#if no wallpaper default to black
[ -z "${wallpaper}" ] && _exec xsetroot -solid "#000000" || \
    _exec feh --bg-scale "${wallpaper}"

terminal_emulator="$(minos-config x-terminal 2>/dev/null)"
[ -z "${terminal_emulator}" ] && terminal_emulator="x-terminal-emulator"
_exec "${terminal_emulator}" -name scratchpad -e "${SHELL}"
_execm m-clipboard autocutsel # sync X/Gnome clipboards
_execm m-eyeshield redshift   # save your eyes
(sleep 1.5 && _execm m-composition compton)& # eyecandy + fix for general tearing
# (sleep 1 && _execm m-composition 'xcompmgr -cCFf -l2 -t1 -r3 -o.20 -D3')&

#_exec urxvtd -q -f -o          # urxvt server, improves performance but it breaks often
#_exec xbanish                  # hide mouse coursor when it isn't used, broken
#_exec unclutter -root -visible # hide mouse coursor when it isn't used, broken
#_exec numlockx on              # numlock on
#_exec setxkbmap -option terminate:ctrl_alt_bksp # Ctrl-Alt-Backspace to kill X
[ -e /tmp/mplayer.fifo ] || _exec mkfifo /tmp/mplayer.fifo # mplayer fifo controller

_exec minos-welcome

if [ -x "${HOME}"/.minos/autostart ] && [ X"${0}" != X"${HOME}"/.minos/autostart ]; then
    exec "${HOME}"/.minos/autostart
fi
