#!/bin/bash
# example file to be used with --hookdir
#
# run lintian on generated deb files
#!/bin/sh
# run lintian

echo "I: installing lintian and running it on the package"
apt-get install -y --force-yes lintian &>/dev/null
echo "++++ Lintian output ++++"
lintian --allow-root --color=always -I /tmp/buildd/*.changes | tee /tmp/buildd/lintian
echo "++++ End lintian output ++++"
