#!/bin/sh

echo "buildresult: $BUILDRESULT"
/usr/bin/dpkg-scanpackages $BUILDRESULT /dev/null > $BUILDRESULT/Packages
#echo "deb file:$BUILDRESULT precise main" >> /etc/apt/sources.list
/usr/bin/apt-get update

# vim: set ts=8 sw=4 tw=0 ft=sh :
